stages:
  preprocess:
    cmd: python src/data/preprocess.py
    deps:
      - src/data/preprocess.py
      - data/raw/insurance_sample_data.csv
      - params.yaml
    params:
      - data
      - preprocessing
    outs:
      - data/processed/cleaned_data.csv
    metrics:
      - reports/metrics/preprocess_metrics.json

  analyze:
    cmd: python src/visualization/create_plots.py
    deps:
      - data/processed/cleaned_data.csv
      - src/visualization/create_plots.py
    params:
      - data
    outs:
      - reports/figures/loss_ratio_by_province.png
      - reports/figures/risk_heatmap.png
      - reports/figures/correlation_matrix.png
    metrics:
      - reports/metrics/eda_metrics.json

  train:
    cmd: python src/models/train_model.py
    deps:
      - data/processed/cleaned_data.csv
      - src/models/train_model.py
    params:
      - model
    outs:
      - models/random_forest.pkl
      - models/linear_regression.pkl
    metrics:
      - reports/metrics/model_metrics.json